import type { Metadata } from "next";
import "./globals.css";
import StyledComponentsRegistry from "./utils/registry";
import { Body, RootContainer } from "./Styles/Styles";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Body className="">
        <Navbar />
        <RootContainer>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </RootContainer>
      </Body>
    </html>
  );
}
