import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./utils/registry";
import { Body } from "./Styles/Styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Body className="">
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </Body>
    </html>
  );
}
